config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'volunteers#index'

  resources :girls, except: :index

  resources :volunteers

  resources :volunteers do
    resources :girls do
      resources :messages, only: [:index, :create]
    end
  end
  post '/languages', to: 'users#set_language', as: 'languages'
  mount ActionCable.server => '/cable'
  post '/new-heally', to: 'girls#new_heally'

  get 'conversation' => 'messages#fake_talk'
  post 'conversation' => 'messages#redirect_to_talk'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  has_secure_password
  # has_attached_file :certification
  # validates_attachment :certification, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_many :volunteer_expertises
  has_many :girl_volunteers
  has_many :expertises, through: :volunteer_expertises
  has_many :girls, through: :girl_volunteers
  has_many :messages
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController

  def index
  end

  def show
    @volunteer = Volunteer.find(current_volunteer_user.id)
  end

  def new
    @volunteer = Volunteer.new
    @expertise_array = ["Safe Sex", "STDs", "Pregnant", "Puberty", "Rape Prevention", "Mental Health"]
  end

  def create
    @volunteer = Volunteer.new(volunteer_params)
      if @volunteer.save
        VolunteerExpertise.create(volunteer: @volunteer, expertise: Expertise.find_or_create_by(name: params[:expertise_1]))
        VolunteerExpertise.create(volunteer: @volunteer, expertise: Expertise.find_or_create_by(name: params[:expertise_2]))
        volunteer?("volunteer")
        log_in_volunteer @volunteer
        redirect_to "/volunteers/#{@volunteer.id}"
      else
        flash[:danger] = "Error creating a new instance of yourself!"
        render 'new'
      end
    end

    private

    def volunteer_params
       params.require(:volunteer).permit(:username, :language, :password)
    end


end

app/views/volunteers/_header.html.erb
<header style="background-color:#F4F7F5">
  <ul class="headerlist">
  <li class="list-float"><a class="list-style" href="default.asp">Home</a></li>
  <li class="list-float"><a class="list-style" href="news.asp">News</a></li>
  <li class="list-float"><a class="list-style" href="contact.asp">Contact</a></li>
  <li class="list-float"><a class="list-style" href="about.asp">About</a></li>

</ul>
</header>

app/views/volunteers/_signup.html.erb
<div class="login-page">

<%= form_for @volunteer,  :class => "register-form" do |f| %>
<div class="form">


  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :language %>
    <%= f.text_field :language, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :certification %>
    <%= f.file_field :certification, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>
  </div>

  <p>Chose two areas of expertise</p>

  <%= select_tag 'expertise_1', options_for_select(@expertise_array) %>

<br>
  <%= select_tag 'expertise_2', options_for_select(@expertise_array) %>

  <br>
  <br>
  <%= f.submit 'Sign Up!', class: 'btn btn-primary' %>
<% end %>
</div>
</div>

app/views/volunteers/index.html.erb
<!DOCTYPE HTML>
<!--
	Massively by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Massively by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!-- <link rel="stylesheet" href="assets/stylesheets/css/main.css" /> -->
		<!-- <noscript><link rel="stylesheet" href="assets/stylesheets/css/noscript.css" /></noscript> -->
	</head>
	<body class="is-loading">

		<!-- Wrapper -->
			<div id="wrapper" class="fade-in">

				<!-- Intro -->
					<div id="intro">
						<h1>Heall </h1>
						<p class="font-comic">Take ownership over your body!
						<br>Get a Health Ally!</p>
						<div class="dropdown"  style="list-style:none;">
							<button class="dropbtn">LANGUAGE</button>
								<div class="dropdown-content">
									<li class="drop">
										<%= link_to t('.english'), languages_path(lang_pref: 'en'), method: :post, :class => "text" %>
										<!-- <a href="/languages" class="lang-pref-opt"><%= t '.english' %></a> -->
									</li>

									<li class="drop">
										<%= link_to t('.spanish'), languages_path(lang_pref: 'es'), method: :post, :class => "text" %>
										<!-- <a href="/languages" class="lang-pref-opt"><%= t '.spanish' %></a> -->
									</li>

									<li class="drop">
										<%= link_to t('.portuguese'), languages_path(lang_pref: 'pt'), method: :post, :class => "text"%>
										<!-- <a href="/languages" class="lang-pref-opt"><%= t '.spanish' %></a> -->
									</li>

								

								</div>
						</div>
						<ul class="actions">
							<li><a href="#header"></a></li>
						</ul>
					</div>

				<!-- Header -->
					<header id="header">
						<a href="index.html" class="logo">Massively</a>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li class="active"><a href="index.html">About</a></li>
							<li><a href="generic.html">Physical Health</a></li>
							<li><a href="elements.html">Mental Health</a></li>
						</ul>

					</nav>

				<!-- Main -->
					<div id="main">

						<!-- Featured Post -->
							<article class="post featured">
								<header class="major">
									<span class="date">June 11, 2017</span>
									<h2><a href="#">Our Goal</a></h2>
									<p class="font-comic" >Young girls all over the world suffer a stigma regarding talking about health issues. A young Syrian refugee girl around the age 16 has many obstacles, for example, not knowing the language, not having the right support, doesnt go to school and is in this ()culture. so we want to connect her with professional who speak her language.
We know that health is important, so being able to educate yourself is essential. A young Syrian girl around the age 16 should be able to know about resources around her and be able to talk to professionals who can help her. </p>
								</header>
								<a href="#" class="image main"></a>
								<ul class="actions">
									<li><a href="#" class="button big">Full Story</a></li>
								</ul>
							</article>



						<!-- Footer -->


					</div>

				

				<!-- Copyright -->
					<div id="copyright">
						<ul><li>&copy; Heall</li><li>Design: <a href="https://html5up.net">Yaritza, Christian, Marcela</a></li></ul>
					</div>

			</div>

		<!-- Scripts -->
			<!-- <script src="assets/javascripts/js/jquery.min.js"></script>
			<script src="assets/javascripts/js/jquery.scrollex.min.js"></script>
			<script src="assets/javascripts/js/jquery.scrolly.min.js"></script>
			<script src="assets/javascripts/js/skel.min.js"></script>
			<script src="assets/javascripts/js/util.js"></script>
			<script src="assets/javascripts/js/main.js"></script> -->

	</body>
</html>

app/views/volunteers/new.html.erb
<%= render partial: "signup" %>

app/views/volunteers/show.html.erb
<h2 style="color:white;display:inline-block;margin: 25px;"> Welcome <%= @volunteer.username %></h2>
<label style="display:inline-block; padding-top:5px;margin-top: 20px;float:right;" class="switch">
  <input type="checkbox">
  <div class="slider round"></div>
</label>

<% @volunteer.girls.each do |girl| %>
  <% if  Message.where(girl_id: girl.id, volunteer_id: @volunteer.id).last && Message.where(girl_id: girl.id, volunteer_id: @volunteer.id).last.created_at%>
    <p><a href="/volunteers/<%=@volunteer.id%>/girls/<%=girl.id%>/messages">Talk to <%= girl.username %></a><small> Last talk at <%= Message.where(girl_id: girl.id, volunteer_id: @volunteer.id).last.created_at.strftime("%a, %b %d at %I:%M")%></small></p>
  <% end %>
<% end %>